FROM aws/codebuild/standard:4.0
RUN apt-get update && \
    apt-get install -y libx11-xcb-dev \
                       libxtst6 \
                       libnss3-dev \
                       libxss1 \
                       libasound2 \
                       libatk-bridge2.0-0 \
                       libgtk-3-0
